### ISSUE TITLE
does not work with latest Capistrano 3

### ISSUE THREAD

**Issue by JeanMertz** [afeld/sshkit-interactive#6]
Should this gem still work with the latest Capistrano 3 versions?

I have the following snippet:

``` ruby
desc 'Run Racksh console'
task :console do
  on primary(:app) do
    within release_path do
      SSHKit.config.backend = SSHKit::Interactive::Backend
      set :pty, true

      execute :rake, :console, "RACK_ENV=#{fetch(:stage)}"
    end
  end
end
```

when running `cap staging console` I can see the `racksh` terminal starting, but no input is possible:

```
$ cap staging console --trace
** Invoke staging (first_time)
** Execute staging
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke bundler:map_bins (first_time)
** Execute bundler:map_bins
** Invoke console (first_time)
** Execute console
DEBUG [66f56f93] Running /usr/bin/env if test ! -d /var/www/staging/current; then echo "Directory does not exist '/var/www/staging/current'" 1>&2; false; fi as deployer@app.domain.com
DEBUG [66f56f93] Command: if test ! -d /var/www/staging/current; then echo "Directory does not exist '/var/www/staging/current'" 1>&2; false; fi
DEBUG [66f56f93] Finished in 0.371 seconds with exit status 0 (successful).
INFO [77044dc0] Running bundle exec rake console RACK_ENV=staging as deployer@app.domain.com
DEBUG [77044dc0] Command: cd /var/www/staging/current && bundle exec rake console RACK_ENV=staging
DEBUG [77044dc0]  bundle exec racksh
DEBUG [77044dc0]  Rack::Shell v1.0.0 started in staging environment.
DEBUG [77044dc0]  Switch to inspect mode.
DEBUG [77044dc0]  >> 
puts 'test'
exit

^Ccap aborted!

/Users/Jean/.gem/ruby/2.0.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:20:in `join'
/Users/Jean/.gem/ruby/2.0.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:20:in `map'
/Users/Jean/.gem/ruby/2.0.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:20:in `execute'
/Users/Jean/.gem/ruby/2.0.0/gems/sshkit-1.7.1/lib/sshkit/coordinator.rb:21:in `each'
/Users/Jean/.gem/ruby/2.0.0/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:55:in `on'
/Users/Jean/code/app/config/capistrano/console.rake:3:in `block in <top (required)>'
/Users/Jean/.gem/ruby/2.0.0/gems/rake-10.1.1/lib/rake/task.rb:236:in `call'
/Users/Jean/.gem/ruby/2.0.0/gems/rake-10.1.1/lib/rake/task.rb:236:in `block in execute'
/Users/Jean/.gem/ruby/2.0.0/gems/rake-10.1.1/lib/rake/task.rb:231:in `each'
/Users/Jean/.gem/ruby/2.0.0/gems/rake-10.1.1/lib/rake/task.rb:231:in `execute'
/Users/Jean/.gem/ruby/2.0.0/gems/rake-10.1.1/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/Users/Jean/.rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/Jean/.gem/ruby/2.0.0/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/Jean/.gem/ruby/2.0.0/gems/rake-10.1.1/lib/rake/task.rb:161:in `invoke'
/Users/Jean/.gem/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:149:in `invoke_task'
/Users/Jean/.gem/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/Jean/.gem/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `each'
/Users/Jean/.gem/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `block in top_level'
/Users/Jean/.gem/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:115:in `run_with_threads'
/Users/Jean/.gem/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:100:in `top_level'
/Users/Jean/.gem/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:78:in `block in run'
/Users/Jean/.gem/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/Jean/.gem/ruby/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
/Users/Jean/.gem/ruby/2.0.0/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:in `run'
/Users/Jean/.gem/ruby/2.0.0/gems/capistrano-3.4.0/bin/cap:3:in `<top (required)>'
/Users/Jean/.gem/ruby/2.0.0/bin/cap:23:in `load'
/Users/Jean/.gem/ruby/2.0.0/bin/cap:23:in `<main>'
Tasks: TOP => console
```

any thoughts?

**Comment by afeld** [comment]
Hmm... try setting `SSHKit.config.backend` before the `on primary` and see if that does the trick.
